// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_lMe7y5xAIPkvBlcSi93mViwBOSRj0u4',
    appId: '1:710093697177:web:f6c6cc1367a443fae78808',
    messagingSenderId: '710093697177',
    projectId: 'film-collection-d20de',
    authDomain: 'film-collection-d20de.firebaseapp.com',
    storageBucket: 'film-collection-d20de.firebasestorage.app',
    measurementId: 'G-HSJ5F94SBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7lNdJv5hyFLIfTGC1b5_DlFK_cSpOCZQ',
    appId: '1:710093697177:android:e5c2b06053feb61fe78808',
    messagingSenderId: '710093697177',
    projectId: 'film-collection-d20de',
    storageBucket: 'film-collection-d20de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR8ahGufcv1eXfVhngwqbN7ZyP0CD6FrU',
    appId: '1:710093697177:ios:a6de60be5e5cc244e78808',
    messagingSenderId: '710093697177',
    projectId: 'film-collection-d20de',
    storageBucket: 'film-collection-d20de.firebasestorage.app',
    iosBundleId: 'com.example.filmCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR8ahGufcv1eXfVhngwqbN7ZyP0CD6FrU',
    appId: '1:710093697177:ios:a6de60be5e5cc244e78808',
    messagingSenderId: '710093697177',
    projectId: 'film-collection-d20de',
    storageBucket: 'film-collection-d20de.firebasestorage.app',
    iosBundleId: 'com.example.filmCollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_lMe7y5xAIPkvBlcSi93mViwBOSRj0u4',
    appId: '1:710093697177:web:ff60717245e3c1c0e78808',
    messagingSenderId: '710093697177',
    projectId: 'film-collection-d20de',
    authDomain: 'film-collection-d20de.firebaseapp.com',
    storageBucket: 'film-collection-d20de.firebasestorage.app',
    measurementId: 'G-HHD008S6E6',
  );
}
